Добрый день. Есть вопросы. В классе IndexingService вызываю рекурсию из объектов класса ParseWebRecursive. В классе ParseWebRecursive я для каждой новой ссылки создаю объект класса ParseWeb и отправляю снова на рекурсию. Также в классе ParseWeb я получаю код HTML страницы, создаю объект Page и сохраняю этот объект в репозиторй PageCRUDService. При этом в классе ParseWeb я указал к элементу PageCRUDService анотацию Autowired. Но сам класс ParseWeb не анотировал как Component. Я не могу его так анотировать, потому что мне для каждой ссылки нужны новые экземпляры класса ParseWeb, которые создаются в классе ParseWebRecursive.Иначе при многопоточности экземпляру класса ParseWeb будет присвоена последняя из списка ссылка и поиск будет проходить только по ней. В общем при запуске приложения и нажатии кнопки StartIndexing выскакивает ошибка "2024-04-03 17:13:53.019 ERROR 21316 --- [nio-8087-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
 java.lang.NullPointerException: Cannot invoke "searchengine.services.PageCRUDService.savePageStatusOk(searchengine.model.entityes.SiteEntity, org.jsoup.nodes.Document, int)" because "this.pageCRUDService" is null"
 Почему Spring не подгружает экземпляр PageCRUDService, если он анотирован @Autowired.
 И как быть в этой ситуации? уходить от трех классов и прописывать весь код в сервисе IndexingService? Тогда этот сервис получится очень загруженным.
 Я уже три дня над этим голову ломаю. Подскажите пожалуйста что с этим делать.